apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: long-streaming-transport
  namespace: buzz-bot
spec:
  forwardingTimeouts:
    responseHeaderTimeout: 30s
    idleConnTimeout: 300s
