apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tg-api-data
  namespace: buzz-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi              # bot API server caches downloaded files here
